# Generated by Django 5.1.1 on 2024-09-04 22:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pausas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_maxima', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pausa',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=datetime.datetime(2024, 9, 4, 22, 27, 51, 911658, tzinfo=datetime.timezone.utc))),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
