# Generated by Django 4.2.10 on 2024-09-05 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0002_configuracaopausa_alter_pausa_inicio_filaespera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 5, 7, 21, 20, 765508, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
