# Generated by Django 5.1.1 on 2024-09-05 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0003_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 5, 16, 7, 28, 901815, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
