


# Generated by Django 5.1.1 on 2024-09-06 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0004_alter_filaespera_data_entrada"),
        ("usuarios", "0002_alter_usuario_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 6, 22, 1, 59, 748796, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="PausasDiarias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(blank=True, null=True)),
                ("fim", models.DateTimeField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
