# Generated by Django 5.1.1 on 2024-09-18 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0005_alter_filaespera_data_entrada_pausasdiarias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 18, 13, 29, 22, 511000, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
