# Generated by Django 5.1.1 on 2024-09-19 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pausas", "0006_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 19, 8, 8, 35, 288086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
