# Generated by Django 5.1.1 on 2024-09-19 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0006_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="pausa",
            name="data_aprovacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 19, 21, 21, 44, 675252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
