# Generated by Django 4.2.10 on 2024-10-04 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0008_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="pausa",
            name="pausa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 4, 8, 27, 52, 558950, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
