# Generated by Django 5.1.1 on 2024-10-17 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0010_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 17, 21, 8, 55, 428487, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
