# Generated by Django 5.1.1 on 2024-10-17 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0011_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 17, 23, 9, 51, 104636, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
