# Generated by Django 5.1.1 on 2024-10-24 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pausas", "0012_alter_filaespera_data_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 24, 23, 10, 42, 258241, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
