# Generated by Django 5.1.1 on 2024-10-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pausas", "0007_alter_filaespera_data_entrada"),
        ("pausas", "0013_alter_filaespera_data_entrada"),
    ]

    operations = []
