# Generated by Django 5.1.1 on 2024-10-28 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pausas", "0014_merge_20241028_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 28, 19, 6, 44, 87235, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
