# Generated by Django 5.1.1 on 2025-01-03 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pausas', '0015_alter_filaespera_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filaespera',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
