# Generated by Django 5.1.5 on 2025-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pausas', '0016_alter_filaespera_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPausa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_maxima', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pausa',
            name='ja_utilizou_pausa',
            field=models.BooleanField(default=False),
        ),
    ]
