# Generated by Django 5.1.1 on 2024-09-18 13:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0002_alter_usuario_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackofficeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidade_maxima", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BackOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(blank=True, null=True)),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("aprovado", models.BooleanField(default=False)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackOfficeDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(blank=True, null=True)),
                ("fim", models.DateTimeField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackOfficeFilaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            9,
                            18,
                            13,
                            29,
                            22,
                            511997,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
