# Generated by Django 5.1.1 on 2024-09-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_alter_backofficefilaespera_data_entrada"),
    ]

    operations = [

        #migrations.AddField(
         #   model_name="backoffice",
          #  name="data_aprovacao",
           # field=models.DateTimeField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name="backofficefilaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 20, 15, 5, 8, 811113, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
