# Generated by Django 4.2.10 on 2024-10-04 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0003_backoffice_data_aprovacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backofficefilaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 4, 8, 27, 52, 563109, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
