# Generated by Django 4.2.10 on 2024-10-04 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0004_alter_backofficefilaespera_data_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="backoffice",
            name="pausa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="backofficefilaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 4, 8, 34, 46, 24320, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
