# Generated by Django 5.1.1 on 2024-10-17 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0005_backoffice_pausa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backoffice",
            name="inicio_pausa",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backoffice",
            name="termo_pausa",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backofficefilaespera",
            name="data_entrada",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 17, 23, 9, 51, 105682, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
