# Generated by Django 5.1.1 on 2024-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0007_backoffice_tempo_ate_pausar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backoffice",
            name="data_aprovacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
