# Generated by Django 4.2.10 on 2025-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0009_backoffice_almoco"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackofficeConfigTarde_BO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidade_maxima", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="backoffice",
            name="bo_ja_em_pausa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backoffice",
            name="turno_manha",
            field=models.BooleanField(default=True),
        ),
    ]
