# Generated by Django 5.1.5 on 2025-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_backofficeconfigtarde_bo_backoffice_bo_ja_em_pausa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeConfigTerceiroBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_maxima', models.IntegerField(default=0)),
            ],
        ),
    ]
