# Generated by Django 6.0 on 2026-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_backofficeconfigterceirobo'),
    ]

    operations = [
        migrations.AddField(
            model_name='backoffice',
            name='ja_utilizou_bo',
            field=models.BooleanField(default=False),
        ),
    ]
