# Generated by Django 6.0 on 2026-01-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_backoffice_ja_utilizou_bo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackofficeConfigTerceiroBO',
        ),
        migrations.RemoveField(
            model_name='backoffice',
            name='ja_utilizou_bo',
        ),
    ]
