# Generated by Django 5.1.5 on 2025-02-04 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_usuario_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interacao', models.CharField(blank=True, max_length=50, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BackOfficeNPS',
            fields=[
            ],
            options={
                'verbose_name': 'BackOffice NPS',
                'verbose_name_plural': 'BackOffice NPS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicador.nps',),
        ),
        migrations.CreateModel(
            name='FrontOfficeNPS',
            fields=[
            ],
            options={
                'verbose_name': 'FrontOffice NPS',
                'verbose_name_plural': 'FrontOffice NPS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicador.nps',),
        ),
    ]
