# Generated by Django 5.1.5 on 2025-02-05 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackOfficeNPS',
        ),
        migrations.DeleteModel(
            name='FrontOfficeNPS',
        ),
        migrations.CreateModel(
            name='BackOfficeNPS',
            fields=[
                ('nps_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicador.nps')),
            ],
            options={
                'verbose_name': 'BackOffice NPS',
                'verbose_name_plural': 'BackOffice NPS',
            },
            bases=('indicador.nps',),
        ),
        migrations.CreateModel(
            name='FrontOfficeNPS',
            fields=[
                ('nps_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indicador.nps')),
            ],
            options={
                'verbose_name': 'FrontOffice NPS',
                'verbose_name_plural': 'FrontOffice NPS',
            },
            bases=('indicador.nps',),
        ),
    ]
