# Generated by Django 5.1.5 on 2025-02-25 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0003_excelfile'),
        ('usuarios', '0011_usuario_ja_utilizou_pausa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotores', models.IntegerField()),
                ('detratores', models.IntegerField()),
                ('neutros', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
