# Generated by Django 5.1.5 on 2025-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0004_historiconps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interlocutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=100)),
                ('destinatarios', models.CharField(max_length=255)),
                ('cc', models.CharField(max_length=255)),
            ],
        ),
    ]
