# Generated by Django 5.1.5 on 2025-02-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0005_interlocutores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocutores',
            name='at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interlocutores',
            name='cc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interlocutores',
            name='destinatarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
