# Generated by Django 5.1.5 on 2025-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0006_alter_interlocutores_at_alter_interlocutores_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiconps',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interlocutores',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interlocutores',
            name='destinatarios',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
