# Generated by Django 5.1.1 on 2024-09-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="usuarios.tipousuario"
            ),
        ),
    ]
