# Generated by Django 4.2.10 on 2025-01-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_usuario_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="turno_manha",
            field=models.BooleanField(default=True),
        ),
    ]
