# Generated by Django 4.2.10 on 2025-01-16 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_usuario_turno_manha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="turno_manha",
        ),
    ]
