# Generated by Django 4.2.10 on 2025-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_remove_usuario_turno_manha"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="turno_manha",
            field=models.BooleanField(default=True),
        ),
    ]
