# Generated by Django 5.1.5 on 2025-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_turno_manha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identificador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
