# Generated by Django 5.1.5 on 2025-02-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.ForeignKey(limit_choices_to={'tipo__nome': 'Supervisor'}, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='equipa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipas'),
        ),
    ]
