# Generated by Django 5.1.5 on 2025-02-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipas',
            old_name='nome',
            new_name='nome_equipa',
        ),
    ]
