# Generated by Django 5.1.5 on 2025-02-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_rename_nome_equipas_nome_equipa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipas',
            old_name='nome_equipa',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='equipas',
            name='lider',
            field=models.ForeignKey(limit_choices_to={'tipo__tipo': 'Supervisor'}, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
