# Generated by Django 5.1.5 on 2025-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_nome_equipa_equipas_nome_alter_equipas_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ja_utilizou_pausa',
            field=models.BooleanField(default=False),
        ),
    ]
