# Generated by Django 5.1.5 on 2025-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_ja_utilizou_pausa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='quantidade_pausas',
            field=models.IntegerField(default=0),
        ),
    ]
