# Generated by Django 5.1.5 on 2025-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_quantidade_pausas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bo_aceite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pausa_aceite',
            field=models.BooleanField(default=False),
        ),
    ]
