# Generated by Django 5.1.5 on 2025-04-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_bo_aceite_usuario_pausa_aceite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='bo_aceite',
            new_name='ultrapassou_tempo_bo',
        ),
    ]
