# Generated by Django 5.1.5 on 2025-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_rename_bo_aceite_usuario_ultrapassou_tempo_bo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
