# Generated by Django 5.1.5 on 2025-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_usuario_tipo_usuario_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
