# Generated by Django 6.0 on 2026-01-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_usuario_beta_usuario_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ja_utilizou_bo',
            field=models.BooleanField(default=False),
        ),
    ]
