# Generated by Django 5.1.5 on 2025-03-26 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darkheka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkheka',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
