# Generated by Django 5.1.5 on 2025-04-03 09:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkheka', '0002_alter_darkheka_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkheka',
            name='keys',
            field=models.CharField(max_length=500, verbose_name='Chaves de pesquisa'),
        ),
        migrations.AlterField(
            model_name='darkheka',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='darkheka',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
