# Generated by Django 5.1.5 on 2025-09-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0001_initial'),
        ('usuarios', '0016_usuario_beta_usuario_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoiqs',
            name='assistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
