# Generated by Django 5.1.5 on 2025-09-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0002_tipoiqs_assistente'),
        ('usuarios', '0016_usuario_beta_usuario_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoiqs',
            name='assistente',
        ),
        migrations.AddField(
            model_name='iqs',
            name='assistente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
