# Generated by Django 5.1.5 on 2025-09-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0003_remove_tipoiqs_assistente_iqs_assistente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoiqs',
            name='updated_at',
        ),
    ]
