# Generated by Django 5.1.5 on 2025-09-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0004_remove_tipoiqs_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqs',
            old_name='assistente',
            new_name='funcionario',
        ),
    ]
