# Generated by Django 5.1.5 on 2025-09-15 22:10

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0005_rename_assistente_iqs_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iqs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='iqs',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='iqs',
            name='data',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
