# Generated by Django 5.1.5 on 2025-09-15 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0007_alter_iqs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqs',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 22, 12, 55, 847027, tzinfo=datetime.timezone.utc)),
        ),
    ]
