# Generated by Django 5.1.5 on 2025-09-15 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqs', '0008_alter_iqs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqs',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
